'use client';
import React, { useState } from 'react';

const { default: BasicTable } = require('@/app/components/BasicTable');

const datas = [
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    BF: 'BF',
    BS: 'BS',
    noSegmen: 'noSegmen',
    noRuta: 'noRuta',
    kodeKota: 'kodeKota',
    kodeKecamatan: 'kodeKecamatan',
    namaKecamatan: 'namaKecamatan',
    kodeDesa: 'kodeDesa',
    namaDesa: 'namaDesa',
    namaKRT: 'namaKRT',
    alamat: 'alamat',
    jumlahISUUP: 'jumlahISUUP',
    noUrutPemilikUUP: 'noUrutPemilikUUP',
    namaPemilikUUP: 'namaPemilikUUP',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'statusKelola',
    lokasiUP: 'lokasiUP',
    jenisUP: 'jenisUP',
    noUrutUUP: 'noUrutUUP',
    latitude: 'latitude',
    longitude: 'longitude',
    akurasi: 'akurasi',
    status: 'status',
    time: 'time',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    BF: 'BF',
    BS: 'BS',
    noSegmen: 'noSegmen',
    noRuta: 'noRuta',
    kodeKota: 'kodeKota',
    kodeKecamatan: 'kodeKecamatan',
    namaKecamatan: 'namaKecamatan',
    kodeDesa: 'kodeDesa',
    namaDesa: 'namaDesa',
    namaKRT: 'namaKRT',
    alamat: 'alamat',
    jumlahISUUP: 'jumlahISUUP',
    noUrutPemilikUUP: 'noUrutPemilikUUP',
    namaPemilikUUP: 'namaPemilikUUP',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'statusKelola',
    lokasiUP: 'lokasiUP',
    jenisUP: 'jenisUP',
    noUrutUUP: 'noUrutUUP',
    latitude: 'latitude',
    longitude: 'longitude',
    akurasi: 'akurasi',
    status: 'status',
    time: 'time',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    BF: 'BF',
    BS: 'BS',
    noSegmen: 'noSegmen',
    noRuta: 'noRuta',
    kodeKota: 'kodeKota',
    kodeKecamatan: 'kodeKecamatan',
    namaKecamatan: 'namaKecamatan',
    kodeDesa: 'kodeDesa',
    namaDesa: 'namaDesa',
    namaKRT: 'namaKRT',
    alamat: 'alamat',
    jumlahISUUP: 'jumlahISUUP',
    noUrutPemilikUUP: 'noUrutPemilikUUP',
    namaPemilikUUP: 'namaPemilikUUP',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'statusKelola',
    lokasiUP: 'lokasiUP',
    jenisUP: 'jenisUP',
    noUrutUUP: 'noUrutUUP',
    latitude: 'latitude',
    longitude: 'longitude',
    akurasi: 'akurasi',
    status: 'status',
    time: 'time',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    BF: 'BF',
    BS: 'BS',
    noSegmen: 'noSegmen',
    noRuta: 'noRuta',
    kodeKota: 'kodeKota',
    kodeKecamatan: 'kodeKecamatan',
    namaKecamatan: 'namaKecamatan',
    kodeDesa: 'kodeDesa',
    namaDesa: 'namaDesa',
    namaKRT: 'namaKRT',
    alamat: 'alamat',
    jumlahISUUP: 'jumlahISUUP',
    noUrutPemilikUUP: 'noUrutPemilikUUP',
    namaPemilikUUP: 'namaPemilikUUP',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'statusKelola',
    lokasiUP: 'lokasiUP',
    jenisUP: 'jenisUP',
    noUrutUUP: 'noUrutUUP',
    latitude: 'latitude',
    longitude: 'longitude',
    akurasi: 'akurasi',
    status: 'status',
    time: 'time',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    BF: 'BF',
    BS: 'BS',
    noSegmen: 'noSegmen',
    noRuta: 'noRuta',
    kodeKota: 'kodeKota',
    kodeKecamatan: 'kodeKecamatan',
    namaKecamatan: 'namaKecamatan',
    kodeDesa: 'kodeDesa',
    namaDesa: 'namaDesa',
    namaKRT: 'namaKRT',
    alamat: 'alamat',
    jumlahISUUP: 'jumlahISUUP',
    noUrutPemilikUUP: 'noUrutPemilikUUP',
    namaPemilikUUP: 'namaPemilikUUP',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'statusKelola',
    lokasiUP: 'lokasiUP',
    jenisUP: 'jenisUP',
    noUrutUUP: 'noUrutUUP',
    latitude: 'latitude',
    longitude: 'longitude',
    akurasi: 'akurasi',
    status: 'status',
    time: 'time',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    BF: 'BF',
    BS: 'BS',
    noSegmen: 'noSegmen',
    noRuta: 'noRuta',
    kodeKota: 'kodeKota',
    kodeKecamatan: 'kodeKecamatan',
    namaKecamatan: 'namaKecamatan',
    kodeDesa: 'kodeDesa',
    namaDesa: 'namaDesa',
    namaKRT: 'namaKRT',
    alamat: 'alamat',
    jumlahISUUP: 'jumlahISUUP',
    noUrutPemilikUUP: 'noUrutPemilikUUP',
    namaPemilikUUP: 'namaPemilikUUP',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'statusKelola',
    lokasiUP: 'lokasiUP',
    jenisUP: 'jenisUP',
    noUrutUUP: 'noUrutUUP',
    latitude: 'latitude',
    longitude: 'longitude',
    akurasi: 'akurasi',
    status: 'status',
    time: 'time',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    BF: 'BF',
    BS: 'BS',
    noSegmen: 'noSegmen',
    noRuta: 'noRuta',
    kodeKota: 'kodeKota',
    kodeKecamatan: 'kodeKecamatan',
    namaKecamatan: 'namaKecamatan',
    kodeDesa: 'kodeDesa',
    namaDesa: 'namaDesa',
    namaKRT: 'namaKRT',
    alamat: 'alamat',
    jumlahISUUP: 'jumlahISUUP',
    noUrutPemilikUUP: 'noUrutPemilikUUP',
    namaPemilikUUP: 'namaPemilikUUP',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'statusKelola',
    lokasiUP: 'lokasiUP',
    jenisUP: 'jenisUP',
    noUrutUUP: 'noUrutUUP',
    latitude: 'latitude',
    longitude: 'longitude',
    akurasi: 'akurasi',
    status: 'status',
    time: 'time',
  },
];

const TableKeseluruhan = () => {
  const columns = [
    {
      accessorKey: 'kodeUUP',
      header: 'Kode UUP',
    },
    {
      accessorKey: 'nimPPL',
      header: 'NIM PPL',
    },
    {
      accessorKey: 'namaPPL',
      header: 'Nama PPL',
    },
    {
      accesssorKey: 'kodeBS',
      header: 'Kode BS',
    },
    {
      accesssorKey: 'BF',
      header: 'BF',
    },
    {
      accesssorKey: 'BS',
      header: 'BS',
    },
    {
      accesssorKey: 'noSegmen',
      header: 'No Segmen',
    },
    {
      accesssorKey: 'noRuta',
      header: 'Nomor Urut RUta',
    },
    {
      accesssorKey: 'kodeKota',
      header: 'Kode Kota',
    },
    {
      accesssorKey: 'kodeKecamatan',
      header: 'Kode Kecamatan',
    },
    {
      accesssorKey: 'namaKecamatan',
      header: 'Nama Kecamatan',
    },
    {
      accesssorKey: 'kodeDesa',
      header: 'Kode Desa',
    },
    {
      accesssorKey: 'namaDesa',
      header: 'Nama Desa',
    },
    {
      accesssorKey: 'namaKRT',
      header: 'Nama KRT',
    },
    {
      accesssorKey: 'alamat',
      header: 'Alamat',
    },
    {
      accesssorKey: 'jumlahISUUP',
      header: 'Jumlah IS UUP',
    },
    {
      accesssorKey: 'noUrutPemilikUUP',
      header: 'Nomo Urut Pemilik UUP',
    },
    {
      accesssorKey: 'namaPemilikUUP',
      header: 'Nama Pemilik UUP',
    },
    {
      accesssorKey: 'keududukanUUP',
      header: 'Kedudukan UUP',
    },
    {
      accesssorKey: 'statusKelola',
      header: 'Status Kelola',
    },
    {
      accesssorKey: 'lokasiUP',
      header: 'Lokasi UP',
    },
    {
      accesssorKey: 'jenisUP',
      header: 'Jenis UP',
    },
    {
      accesssorKey: 'noUrutUUP',
      header: 'Nomor Urut UUP',
    },
    {
      accesssorKey: 'latitude',
      header: 'Latitude',
    },
    {
      accesssorKey: 'longitude',
      header: 'Longitude',
    },
    {
      accesssorKey: 'akurasi',
      header: 'Akurasi',
    },
    {
      accesssorKey: 'status',
      header: 'Status',
    },
    {
      accesssorKey: 'time',
      header: 'Time',
    },
  ];

  return (
    <>
      <BasicTable columns={columns} data={datas} />
    </>
  );
};

export default TableKeseluruhan;
