'use client';
import React, { useState } from 'react';

const { default: BasicTable } = require('@/app/components/BasicTable');

const datas = [
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '31',
    bs: '3313',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
];

const TableKeseluruhan = () => {
  const columns = [
    {
      accessorKey: 'kodeUUP',
      header: 'Kode UUP',
    },
    {
      accessorKey: 'nimPPL',
      header: 'NIM PPL',
    },
    {
      accessorKey: 'namaPPL',
      header: 'Nama PPL',
    },
    {
      accessorKey: 'kodeBS',
      header: 'Kode BS',
    },
    {
      accessorKey: 'bf',
      header: 'BF',
    },
    {
      accessorKey: 'bs',
      header: 'BS',
    },
    {
      accessorKey: 'noSegmen',
      header: 'No Segmen',
    },
    {
      accessorKey: 'noRuta',
      header: 'Nomor Urut RUta',
    },
    {
      accessorKey: 'kodeKota',
      header: 'Kode Kota',
    },
    {
      accessorKey: 'kodeKecamatan',
      header: 'Kode Kecamatan',
    },
    {
      accessorKey: 'namaKecamatan',
      header: 'Nama Kecamatan',
    },
    {
      accessorKey: 'kodeDesa',
      header: 'Kode Desa',
    },
    {
      accessorKey: 'namaDesa',
      header: 'Nama Desa',
    },
    {
      accessorKey: 'namaKRT',
      header: 'Nama KRT',
    },
    {
      accessorKey: 'alamat',
      header: 'Alamat',
    },
    {
      accessorKey: 'jumlahISUUP',
      header: 'Jumlah IS UUP',
    },
    {
      accessorKey: 'noUrutPemilikUUP',
      header: 'Nomo Urut Pemilik UUP',
    },
    {
      accessorKey: 'namaPemilikUUP',
      header: 'Nama Pemilik UUP',
    },
    {
      accessorKey: 'keududukanUUP',
      header: 'Kedudukan UUP',
    },
    {
      accessorKey: 'statusKelola',
      header: 'Status Kelola',
    },
    {
      accessorKey: 'lokasiUP',
      header: 'Lokasi UP',
    },
    {
      accessorKey: 'jenisUP',
      header: 'Jenis UP',
    },
    {
      accessorKey: 'noUrutUUP',
      header: 'Nomor Urut UUP',
    },
    {
      accessorKey: 'latitude',
      header: 'Latitude',
    },
    {
      accessorKey: 'longitude',
      header: 'Longitude',
    },
    {
      accessorKey: 'akurasi',
      header: 'Akurasi',
    },
    {
      accessorKey: 'status',
      header: 'Status',
    },
    {
      accessorKey: 'time',
      header: 'Time',
    },
  ];

  return (
    <>
      <BasicTable columns={columns} data={datas} />
    </>
  );
};

export default TableKeseluruhan;
