'use client';
import React, { useState } from 'react';

const { default: BasicTable } = require('@/app/components/BasicTable');

const datas = [
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '31',
    bs: '3313',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
  {
    kodeUUP: '3507040001013B',
    nimPPL: '22231231312',
    namaPPL: 'Ridho',
    kodeBS: '86',
    bf: '11',
    bs: '3132',
    noSegmen: '2123123',
    noRuta: '1313',
    kodeKota: '2131',
    kodeKecamatan: '1212',
    namaKecamatan: 'Badung Selatan',
    kodeDesa: '3232423',
    namaDesa: 'SukaMaju',
    namaKRT: 'RT001',
    alamat: 'Jalanin Aja Dulu',
    jumlahISUUP: '15',
    noUrutPemilikUUP: '10',
    namaPemilikUUP: 'Agus Riyanto',
    keududukanUUP: 'keududukanUUP',
    statusKelola: 'Milik Sendiri',
    lokasiUP: 'Desa',
    jenisUP: 'Menegah',
    noUrutUUP: '003',
    latitude: '-6,23123',
    longitude: '12,313213',
    akurasi: '99%',
    status: 'aktif',
    time: '10:00:01 wib',
  },
];

const TableKeseluruhan = ({data}) => {
  const columns = [
    {
      accessorKey: 'kode_ruta',
      header: 'Kode Ruta',
    },
    {
      accessorKey: 'nim_pencacah',
      header: 'NIM PPL',
    },
    {
      accessorKey: 'nama',
      header: 'Nama PPL',
    },
    {
      accessorKey: 'id_bs',
      header: 'ID BS',
    },
    {
      accessorKey: 'no_bf',
      header: 'BF',
    },
    {
      accessorKey: 'no_bs',
      header: 'BS',
    },
    {
      accessorKey: 'no_segmen',
      header: 'No Segmen',
    },
    {
      accessorKey: 'no_urut_ruta',
      header: 'Nomor Urut RUta',
    },
    {
      accessorKey: 'nama_krt',
      header: 'Nama KRT',
    },
    {
      accessorKey: 'alamat',
      header: 'Alamat',
    },
    // {
    //   accessorFn: (row) => `${row.jml_genx_anak}+${row.jml_genz_dewasa}`,
    //   header: 'Jumlah IS UUP',
    // },
    {
      accessorKey: 'jml_genz_anak',
      header: 'Jumlah Gen Z Anak',
    },
    {
      accessorKey: 'jml_genz_dewasa',
      header: 'Jumlah Gen Z Dewasa',
    },
    // {
    //   accessorKey: 'status',
    //   header: 'Status',
    // },
  ];

  return (
    <>
      <BasicTable columns={columns} data={data} />
    </>
  );
};

export default TableKeseluruhan;
